# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='picture',
        ),
        migrations.AlterField(
            model_name='pupil',
            name='address',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='address',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.FileField(upload_to=''),
        ),
    ]
