# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170724_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=75)),
            ],
        ),
    ]
