# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
