# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-22 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190721_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='birth_date',
            field=models.DateField(blank=True, default='<jamming-date>', null=True),
        ),
    ]
