# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
