# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190721_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_acronym',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
