# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_school_school_acronym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_acronym',
            new_name='acronym',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_images'),
        ),
    ]
