# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200323_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='left_early',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason_of_leaving',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_images'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_images'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_images'),
        ),
    ]
