# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='responsible',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.Responsible'),
        ),
    ]
