# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20170821_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Responsible'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
