# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_pupil_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='enrolment_date',
            field=models.DateField(null=True),
        ),
    ]
