# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20170821_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiement', models.CharField(max_length=255)),
            ],
        ),
    ]
