# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_scholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
