# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20170822_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade_id',
        ),
    ]
