# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20170920_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='grade_id',
        ),
    ]
