# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20170920_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecorded',
            name='score_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
