# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 15:36
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='eSchool/media/documents'), upload_to=''),
        ),
    ]
