# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20171008_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
