# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20171015_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerecorded',
            name='averrage',
        ),
        migrations.RemoveField(
            model_name='scorerecorded',
            name='score_total',
        ),
        migrations.AlterField(
            model_name='scorerecorded',
            name='score_first_control',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scorerecorded',
            name='score_fourth_control',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scorerecorded',
            name='score_second_control',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scorerecorded',
            name='score_third_control',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
